In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
print("Data type of array 1 is : ",array1.dtype)

Data type of array 1 is :  int64


In [4]:
type(array1)

numpy.ndarray

In [6]:
array2d_1 = np.array([[1,2,3],[4,5,6]])
array2d_2 = np.array([[7,8,9],[3,6,1]])
sum_array = array2d_1+array2d_2
print("\nFirst 2D Array:\n", array2d_1)
print("Second 2D Array:\n", array2d_2)
print("Sum of the arrays :\n",sum_array)


First 2D Array:
 [[1 2 3]
 [4 5 6]]
Second 2D Array:
 [[7 8 9]
 [3 6 1]]
Sum of the arrays :
 [[ 8 10 12]
 [ 7 11  7]]


In [13]:
concat_rows = np.concatenate([array2d_1,array2d_2],axis = 0)
concat_columns = np.concatenate([array2d_1,array2d_2],axis=1)
concat_rows
concat_columns

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 3, 6, 1]])

In [15]:
flatenned_array=concat_rows.flatten()
flatenned_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 6, 1])

In [22]:
identity_matrix = np.identity(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)
print("Shape of Identity Matrix:", identity_matrix.shape)
print("Number of Dimensions:", identity_matrix.ndim)
print("Data Type:", identity_matrix.dtype)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of Identity Matrix: (3, 3)
Number of Dimensions: 2
Data Type: float64


In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.impute import SimpleImputer

In [25]:
df=pd.read_csv("loan.csv")
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [26]:
df.drop(columns=['Loan_ID'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             601 non-null    object 
 1   Married            611 non-null    object 
 2   Dependents         599 non-null    object 
 3   Education          614 non-null    object 
 4   Self_Employed      582 non-null    object 
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object 
 11  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB


In [28]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [29]:
categorical_cols=df.select_dtypes(include=['object']).columns
imputer_cat = SimpleImputer(strategy='most_frequent')
df[categorical_cols]= imputer_cat.fit_transform(df[categorical_cols])

In [32]:
df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [34]:
numerical_cols=df.select_dtypes(include='number').columns
imputer_num=SimpleImputer(strategy='median')
df[numerical_cols]=imputer_num.fit_transform(df[numerical_cols])

In [35]:
df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No           5849.0   
1   Male     Yes          1      Graduate            No           4583.0   
2   Male     Yes          0      Graduate           Yes           3000.0   
3   Male     Yes          0  Not Graduate            No           2583.0   
4   Male      No          0      Graduate            No           6000.0   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [36]:
label_encoders = {}
for col in categorical_cols:
    label_encoders[col]=LabelEncoder()
    df[col]=label_encoders[col].fit_transform(df[col])


In [40]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [41]:
df['Loan_Status'].value_counts()

Loan_Status
1    422
0    192
Name: count, dtype: int64

In [42]:
df['Loan_Status'].value_counts(normalize=True)

Loan_Status
1    0.687296
0    0.312704
Name: proportion, dtype: float64

In [43]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0           5849.0   
1       1        1           1          0              0           4583.0   
2       1        1           0          0              1           3000.0   
3       1        1           0          1              0           2583.0   
4       1        0           0          0              0           6000.0   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [45]:
X = df.drop(columns=['Loan_Status']) #Features
y = df['Loan_Status'] #target variable

In [48]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression(solver='liblinear')
rfe_selector=RFE(estimator=log_reg,n_features_to_select=5)
X_rfe=rfe_selector.fit_transform(X,y)
rfe_selected_features=X.columns[rfe_selector.get_support()]
print("RFE selected Features:",rfe_selected_features.tolist())

RFE selected Features: ['Gender', 'Married', 'Education', 'Credit_History', 'Property_Area']


In [49]:
X_rfe

array([[1., 0., 0., 1., 2.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 2.],
       ...,
       [1., 1., 0., 1., 2.],
       [1., 1., 0., 1., 2.],
       [0., 0., 0., 0., 1.]], shape=(614, 5))

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X_rfe, y , test_size=0.2, stratify=y, random_state=42)

In [52]:
print("X_train:",X_train.shape)
print("X_test:",X_test.shape)
print("y_train:",y_train.shape)
print("y_train:",y_test.shape)

X_train: (491, 5)
X_test: (123, 5)
y_train: (491,)
y_train: (123,)


In [53]:
nb_model=GaussianNB()
nb_model.fit(X_train,y_train)

GaussianNB()

In [55]:
y_pred=nb_model.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0])

In [56]:
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Accuracy: 0.8536585365853658
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.55      0.70        38
           1       0.83      0.99      0.90        85

    accuracy                           0.85       123
   macro avg       0.89      0.77      0.80       123
weighted avg       0.87      0.85      0.84       123

Confusion Matrix:
 [[21 17]
 [ 1 84]]


In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [69]:
df=pd.read_csv("train_clean_data.csv")
df.head()

Unnamed: 0   Loan_ID Dependents  ApplicantIncome  CoapplicantIncome  \
0           1  LP001003          1             4583             1508.0   
1           2  LP001005          0             3000                0.0   
2           3  LP001006          0             2583             2358.0   
3           4  LP001008          0             6000                0.0   
4           5  LP001011          2             5417             4196.0   

   LoanAmount  Loan_Amount_Term  Credit_History  gender_Male  married_Yes  \
0       128.0             360.0             1.0            1            1   
1        66.0             360.0             1.0            1            1   
2       120.0             360.0             1.0            1            1   
3       141.0             360.0             1.0            1            0   
4       267.0             360.0             1.0            1            1   

   education_Not Graduate  property_area_Semiurban  property_area_Urban  \
0                       0                        0                    0   
1                       0                        0                    1   
2                       1                        0                    1   
3                       0                        0                    1   
4                       0                        0                    1   

   self_employed_Yes  Loan_status_Y  
0                  0              0  
1                  1              1  
2                  0              1  
3                  0              1  
4                  1              1

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Unnamed: 0               517 non-null    int64  
 1   Loan_ID                  517 non-null    object 
 2   Dependents               517 non-null    object 
 3   ApplicantIncome          517 non-null    int64  
 4   CoapplicantIncome        517 non-null    float64
 5   LoanAmount               517 non-null    float64
 6   Loan_Amount_Term         517 non-null    float64
 7   Credit_History           517 non-null    float64
 8   gender_Male              517 non-null    int64  
 9   married_Yes              517 non-null    int64  
 10  education_Not Graduate   517 non-null    int64  
 11  property_area_Semiurban  517 non-null    int64  
 12  property_area_Urban      517 non-null    int64  
 13  self_employed_Yes        517 non-null    int64  
 14  Loan_status_Y            5

In [71]:
df.shape

(517, 15)

In [72]:
df['Loan_status_Y'].value_counts()

Loan_status_Y
1    360
0    157
Name: count, dtype: int64

In [73]:
X=df.drop(['Loan_ID','Dependents','Loan_status_Y'],axis=1)
y=df['Loan_status_Y']

In [74]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [75]:
!pip install --upgrade scikit-learn
!pip install --upgrade imbalanced-learn

  Using cached scikit_learn-1.7.0-cp313-cp313-win_amd64.whl.metadata (14 kB)
Using cached scikit_learn-1.7.0-cp313-cp313-win_amd64.whl (10.7 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1


  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.0 which is incompatible.


  Using cached scikit_learn-1.6.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Using cached scikit_learn-1.6.1-cp313-cp313-win_amd64.whl (11.1 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.7.0
    Uninstalling scikit-learn-1.7.0:
      Successfully uninstalled scikit-learn-1.7.0


In [78]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=42)
X_train_res,y_train_res=smote.fit_resample(X_train,y_train)

In [79]:
X_train_res.shape

(576, 12)

In [80]:
y_train_res.shape

(576,)